language: python
python: 
  - 3.7

notifications:
  email: false

sudo: false

before_install:
  - pip install numpy
  - pip install codecov
  - pip install coverage

install: true

script:
  - coverage run test.py

after_success:
  - codecov -t "15d2f85f-eb8c-4863-acdd-b5dd3b2b79ac"
