language: python
python: 
  - 3.7

notifications:
  email: false

sudo: false

before_install:
  - pip install numpy
  - pip install codecov
  - pip install coverage

install: true

script:
  - coverage run test.py

after_success:
  - codecov
